<?php

namespace Hospital\PacienteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IngresoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngresoRepository extends EntityRepository
{
}
