<?php

namespace Hospital\PacienteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacienteRepository extends EntityRepository
{
}
