parameters:
#    paciente.example.class: Hospital\PacienteBundle\Example

services:
#    paciente.example:
#        class: %paciente.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
